version: '3.8'

services:
  app:
    build: .
    container_name: app
    restart: on-failure
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mongo
    container_name: db
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - ./.database:/data/db
    environment:
      - MONGO_INITDB_DATABASE=recognition
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
